### ISSUE TITLE
plot missing highest degree point

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/cyChart#26]
Steps to reproduce

1. STRING disease query: breast cancer
2. Run Analyze Network
3. Show Node Degree Dist

Observered: plot missing point at 51.

![Screen Shot 2019-09-06 at 2 22 30 PM](https://user-images.githubusercontent.com/1418193/64461371-db630800-d0b1-11e9-9f56-0bb49f0dd20c.png)

![Screen Shot 2019-09-06 at 2 22 57 PM](https://user-images.githubusercontent.com/1418193/64461368-d736ea80-d0b1-11e9-9c93-19ca8513c26b.png)

**Comment by AdamStuart** [comment]
I believe this is a smoothing issue.  The highest degree point is split between bins.
